### ISSUE TITLE
What tools do you use on a daily basis?

### ISSUE THREAD

**Issue by arthurvr** [jessecogollo/ama#6]

**Comment by jessecogollo** [comment]
hey @arthurvr good day.
principal language nodejs.
editor (GUI): sublimeText but lastly I am trying visual studio code.
editor (terminal): emacs
database: mongodb

what about you?

**Comment by arthurvr** [comment]
I use Vim, iTerm and Google Chrome. Although I've heard a lot of positive stuff about [Spacemacs](http://spacemacs.org/) and [hyper.js](https://github.com/timshadel/hyper-js), so I'm gonna have to try those one day.
