### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [jessecogollo/ama#7]

**Comment by jessecogollo** [comment]
Hi @jedireza I like share mi "knowledge".
at medellin exists a meetup called medellinjs and every month we participate in talks.
but personally I am very shame.

what about you?

**Comment by jedireza** [comment]
Yup, I help co-organize the [NodeSchool SF chapter](http://nodeschool.io/sanfrancisco/). :+1:

**Comment by jessecogollo** [comment]
Sound great !! Some day I should to visit SF...
